version: '3.8'

services:
  vue-app:
    build: ./Gisapp
    ports:
      - "8080:8080"
    volumes:
      - ./Gisapp:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run serve
    networks:
      - Gisnet

  flask-app:
    build: ./GisBack
    ports:
      - "5000:5000"
    environment:
      - SOME_ENV_VARIABLE=value
    networks:
      - Gisnet

  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_DB: gisDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5440:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./Gisdata/export.sql:/docker-entrypoint-initdb.d/export.sql
    networks:
      - Gisnet

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports: 
      - "80:80"
    networks:
      - Gisnet

networks:
  Gisnet:
    external: true

volumes:
  postgres_data:
