version: '3.8'
services:
  vue-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - Gisnet
    environment:
      - NODE_ENV=development
    command: npm run serve

networks:
  Gisnet:
    external: true